### ISSUE TITLE
ArrayIndexOutOfBoundsException in parser

### ISSUE THREAD

**Issue by pcy190** [netplex/json-smart-v1#10]
The parser fails to throw the ParseException when the parser read the unclosed `'`, the following example input could cause the ArrayIndexOutOfBoundsException:
```
'c
```
In detail, when the parser tries to find closed single quotation mark using `indexOf` function, the iteration variable is not sets corretly in line 79:

https://github.com/netplex/json-smart-v1/blob/4e6596fca7ffb7d9008684f3d0de179c733df158/json-smart/src/main/java/net/minidev/json/parser/JSONParserByteArray.java#L78-L83

It shouldn't be the `pos` to be checked less than `len`. Instead, the `i` should be checked. The correct way in line 79 is:
```
for (int i = pos; i < len; i++) 
```

Any input with unclosed single quotation mark could trigger this. Like the input of `'c`, cause the ArrayIndexOutOfBoundsException

**Comment by UrielCh** [comment]
Merged, and published as V1.3.3

**Comment by UrielCh** [comment]
https://mvnrepository.com/artifact/net.minidev/json-smart/1.3.3
