### ISSUE TITLE
parser creates BigDecimals but toJSONString() can't handle them

### ISSUE THREAD

**Issue by jlopez** [netplex/json-smart-v1#2]
This will return a `BigDecimal`:

```
JSONValue.parse("0.050000000000000003"); // returns BigDecimal(3)
```

But a `BigDecimal` will be silently stringified as `{}`:

```
JSONValue.toJSONString(new BigDecimal(1)); // returns "{}"
```

This makes json-smart unable to consume its own JSON strings if any numbers exceed the precision of a double (thus causing the parser to use a `BigDecimal`)

```
String bad = "0.050000000000000003";
assertEquals(JSONValue.toJSONString(JSONValue.parse(bad)), bad); // Fails
```

**Comment by UrielCh** [comment]
Fixed.
