### ISSUE TITLE
Missing release tags

### ISSUE THREAD

**Issue by ebourg** [netplex/json-smart-v1#4]
Hi,

The repository is missing the release tags, could you please consider adding them? If I'm not mistaken here are the commits for each version:

```
git tag 1.3.1 70a6bb2
git tag 1.3   4fe12e8
git tag 1.2   feaf7d1
git tag 1.1.1 3d38b84
git tag 1.1   535d7ac
```

Thank you

**Comment by ipince** [comment]
@ebourg Thank you so much for this.

**Comment by UrielCh** [comment]
may I push those tags to the git without force commiting it ?

**Comment by ebourg** [comment]
Yes, `git push --tags` is enough

**Comment by UrielCh** [comment]
yes it works, but only on my local git, is this possible to push those tag to github?

**Comment by ebourg** [comment]
If you do `git push origin --tags` this will push the local tags to the remote GitHub repository.

**Comment by UrielCh** [comment]
thx tags are now pushed to the main git.

**Comment by ebourg** [comment]
Thank you
