### ISSUE TITLE
Clarify Release Versions

### ISSUE THREAD

**Issue by lcoller** [netplex/json-smart-v1#9]
There is a discrepancy on the last released.  It is tagged with 1.3.2, but the release is called v 1.3.1.

**Comment by UrielCh** [comment]
oops,

let switch to the new version 1.3.3, and forget V1.3.2 and 1.3.1.

the version should be available within ours.

**Comment by UrielCh** [comment]
Is it fixed now ?

**Comment by UrielCh** [comment]
https://mvnrepository.com/artifact/net.minidev/json-smart/1.3.3
is publushed
